### ISSUE TITLE
4.54.0 seems to have removed homebridge entirely?

### ISSUE THREAD

**Issue by jonnyborbs** [oznu/homebridge-config-ui-x#1912]
### Describe The Bug

Installed 4.54.0 from the plugin update prompt, and immediately my browser redirected to a canned 500 internal server error. Went to the actual server shell to restart homebridge, and discovered it's just completely gone. There's no longer an `hb-config` command to run, or `hb-service`, the commands are just gone. I still have a `homebridge` daemon running but I don't think it will last long in memory only. Something is very wrong here.

### Homebridge UI Version

4.54.0

### Homebridge Version

Not sure now, it was current but now I do not know how to check

### Node.js Version

20.10.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by testpaul999** [comment]
Same here after update to new ui version all files disappear 
Have no longer /usr/local/lib/node_modules/homebridgeßconfig-ui-x/dist/bin/hb-service.js
Nothing run

**Comment by schemers** [comment]
Same here. This symlink seems to broken?

```
pi@homebridge:~ $ ls -l /opt/homebridge/lib/node_modules/homebridge-config-ui-x
lrwxrwxrwx 1 pi pi 8 Dec  7 11:37 /opt/homebridge/lib/node_modules/homebridge-config-ui-x -> ../.54.0

```

**Comment by Krillle** [comment]
Same here

**Comment by jonnyborbs** [comment]
It's more than a broken symlink I fear. I still have the `/usr/local/sbin/hb-config` file but it's now a 1 byte empty file. I can't even run the config utility.

**Comment by devenbj** [comment]
I had a slightl different experience... started with the 500 error.

 I was unable to execute the hb-service commands as I was told I needed to run as root or with sudo... I tried root, sudo, and root with sudo... same error. I remove and install homebridge from apt (I'm on Ubuntu 22.04) and reinstall my plugins. Everything returns to prior. Still prompts for the upgrade. I tried it a second time with the exact same results.

**Comment by town3r** [comment]
+1

hb-service command not found

**Comment by jonnyborbs** [comment]
Using the official HB image I don't even know where to begin attempting to reinstall the packages, and certainly don't want to rebuild - would appreciate maintainer guidance on how we can recover here.

**Comment by ItsHaysus** [comment]
I get a 500 internal server error after an upgrade, no HB-Service to restart

**Comment by aure-olivier** [comment]
Same here ☝️

**Comment by Madcat-76310** [comment]
Same here...

**Comment by benrabicoff** [comment]
Same for me.

**Comment by drheck** [comment]
Same here - how to go back?

**Comment by noelhibbard** [comment]
Whoopsie

Same problem.

**Comment by Wrangler-93** [comment]
Same here, running in Docker , did a "Re deploy" in Portainer and everything came back as it was before (Only needed to update Node)

**Comment by michaelyork** [comment]
Same here

**Comment by aure-olivier** [comment]
> Same here, running in Docker , did a "Re deploy" in Portainer and everything came back as it was before (Only needed to update Node)

Same for me, I just destroyed/recreated the container and it is back with previous homebridge-ui version. FYI, running HB in Docker on Synology NAS

**Comment by noelhibbard** [comment]
> Same here, running in Docker , did a "Re deploy" in Portainer and everything came back as it was before (Only needed to update Node)

I can confirm this worked for me too. Well, not with portainer but with docker compose (down/up).

**Comment by Marco-Erlangen** [comment]
Same here.... Yesterday everything was completely reinstalled and everything was up to date. Made the update today.
500 internal server error

**Comment by town3r** [comment]
Sadly `sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.53.0` doesn't resolve the issue. :(

**Comment by jonnyborbs** [comment]
I used the recommended reinstall steps for the UI plugin

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

This got me to the point where the config UI reloaded, but it gave me a warning that the UI was out of sync with the core server version and prompted a restart. Nothing to lose at this point so I allowed it to try. 

These are the logs from that attempt:

```
Dec  7 12:17:46 homebridge systemd[1]: Starting Homebridge...
Dec  7 12:17:46 homebridge run-parts[7432]: Ensuring /var/lib/homebridge is owned by pi
Dec  7 12:17:46 homebridge run-parts[7434]: Setting port 8581 in /etc/nginx/sites-available/homebridge.local
Dec  7 12:17:46 homebridge run-parts[7434]: Reloading nginx...
Dec  7 12:17:46 homebridge systemd[7466]: homebridge.service: Executable /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js missing, skipping: Permission denied
Dec  7 12:17:46 homebridge systemd[1]: Started Homebridge.
Dec  7 12:17:46 homebridge systemd[7468]: homebridge.service: Failed to locate executable /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js: Permission denied
Dec  7 12:17:46 homebridge systemd[7468]: homebridge.service: Failed at step EXEC spawning /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js: Permission denied
Dec  7 12:17:46 homebridge systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
Dec  7 12:17:46 homebridge systemd[1]: homebridge.service: Failed with result 'exit-code'.
Dec  7 12:17:49 homebridge systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 22.
Dec  7 12:17:49 homebridge systemd[1]: Stopped Homebridge.
```

Yes, I see the permission denied message. But I still do not have any core homebridge binaries on this system anymore.

**Comment by testpaul999** [comment]
Possible solution 
- download version 4.53.0 from GitHub
- Remove link who found at  /usr/local/lib/node_modules/homebridge-config-ui-x/
- Extract the tar.gz and copy the part homebridge-config-ui-x to /usr/local/lib/node_modules/
- For me all run fine now at the old version

**Comment by Madcat-76310** [comment]
Can you show the commands used (for beginner) ?

**Comment by noelhibbard** [comment]
> Can you show the commands used (for beginner) ?

If you are using the official docker image with docker compose, these commands will get you back up:
```bash
docker compose down
docker compose up -d
```

**Comment by hibjoe** [comment]
`sudo apt reinstall homebridge`
works on Raspberry Pi 👍

**Comment by Krillle** [comment]
> Sadly `sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.53.0` doesn't resolve the issue. :(

The update was installed via `/opt/homebridge/lib/node_modules/homebridge-config-ui-x/upgrade-install.sh 4.54.0 /opt/homebridge`, can this be used to downgrade to 4.53.0?

**Comment by nexusis7** [comment]
killed mine too had to recreate image from docker and restore backup

**Comment by nexusis7** [comment]
The purge has begun

**Comment by magnus319** [comment]
> Sadly `sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.53.0` doesn't resolve the issue. :(

It worked for me by just trying to reinstall 4.54.0

**Comment by noelhibbard** [comment]
> killed mine too had to recreate image from docker and restore backup

You may want to adjust your docker-compose.yml to mount /homebridge externally. That way your config and plugins aren't wiped out if you down/up. Like this for example:
```yml
version: '3.8'
services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    environment:
      - TZ=America/New_York
    volumes:
      - ./homebridge-data:/homebridge
```

**Comment by schemers** [comment]
> sudo apt reinstall homebridge 👍

this worked for me, still had all my old configs, etc 🙇 

**edit**: I did notice it downgraded Node back to `18.*`, I ran `sudo hb-service update-node` to get it back to `20.10.0`.

**Comment by town3r** [comment]
> > sudo apt reinstall homebridge 👍
> 
> 
> 
> this worked for me, still had all my old configs, etc 🙇 

I get `Unable to locate package homebridge`

**Comment by kolorfilm** [comment]
> `sudo apt reinstall homebridge` works on Raspberry Pi 👍

this somehow takes forever in my case. stuck at 60%.

**Comment by jonnyborbs** [comment]
`sudo apt reinstall homebridge` does not work on my official RPi image, but I do see that the `homebridge` package is not installed.

FWIW, a regular `install` does not work either.

```
pi@homebridge:/usr/local/sbin $ sudo apt reinstall homebridge
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package homebridge
pi@homebridge:/usr/local/sbin $ sudo apt install homebridge
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package homebridge
pi@homebridge:/usr/local/sbin $ 
```

**Comment by Krillle** [comment]
> > Sadly `sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.53.0` doesn't resolve the issue. :(
> 
> It worked for me by just trying to reinstall 4.54.0

What exactly did you do? Like this:
`sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.54.0`

**Comment by noelhibbard** [comment]
Those not running homebridge in docker should seriously consider it. So much less hassle.

**Comment by jonnyborbs** [comment]
It doesn't help that the entire `homebridge` repo wiki is broken. Is homebridge dead?

Every link here 404s
https://github.com/homebridge/homebridge/wiki

**Comment by AntCardFR** [comment]
For synology package :
Just uninstall + reinstall > No config lost :)

**Comment by Gobias64** [comment]
> `sudo apt reinstall homebridge` does not work on my official RPi image, but I do see that the `homebridge` package is not installed.
> 
> FWIW, a regular `install` does not work either.
> 
> ```
> pi@homebridge:/usr/local/sbin $ sudo apt reinstall homebridge
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package homebridge
> pi@homebridge:/usr/local/sbin $ sudo apt install homebridge
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package homebridge
> pi@homebridge:/usr/local/sbin $ 
> ```

Same here.

**Comment by benrabicoff** [comment]
`sudo apt reinstall homebridge` brought everything back, including config files on my official RPi image

**Comment by jonnyborbs** [comment]
Crosslinking to this issue: https://github.com/homebridge/homebridge/issues/3505

**Comment by nexusis7** [comment]
hard to believe that they didnt test to see if it was working before releasing it?

**Comment by kolorfilm** [comment]
> > `sudo apt reinstall homebridge` works on Raspberry Pi 👍
> 
> this somehow takes forever in my case. stuck at 60%.

it worked. seemed just not update my terminal. I rebooted the pi and then I was back on the old version.

**Comment by Staubgeborener** [comment]
Glad to hear I'm not the only one. Going back was easy in docker with `docker compose down && docker compose up -d`

This one needs a fix asap.

**Comment by jonnyborbs** [comment]
So there isn't even a `homebridge` package in the apt repositories anymore.

```
pi@homebridge:/usr/local/sbin $ sudo apt update
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf Packages [400 kB]
Fetched 447 kB in 2s (192 kB/s)   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
pi@homebridge:/usr/local/sbin $ sudo apt list | grep home

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

debian-edu-artwork-homeworld/oldstable 2.11.6-1 all
golang-github-mitchellh-go-homedir-dev/oldstable 1.1.0-1 all
hdhomerun-config/oldstable 20210210-1 armhf
homebank-data/oldstable 5.5.2-1 all
homebank/oldstable 5.5.2-1 armhf
homer-api-mysql/oldstable 5.0.6+dfsg2-3.2 armhf
homer-api-postgresql/oldstable 5.0.6+dfsg2-3.2 armhf
homer-api/oldstable 5.0.6+dfsg2-3.2 armhf
homesick/oldstable 1.1.6-3 all
kodi-pvr-hdhomerun-dbg/oldoldstable 3.5.0-1~buster armhf
kodi-pvr-hdhomerun/oldoldstable 3.5.0-1~buster armhf
libfile-homedir-perl/oldstable 1.006-1 all
libfile-save-home-perl/oldstable 0.11-1 all
libhdhomerun-dev/oldstable 20210210-1 armhf
libhdhomerun4/oldstable 20210210-1 armhf
librust-home-dev/oldstable 0.5.1-1 armhf
minetest-mod-homedecor/oldstable 20200604.1-1 all
oddjob-mkhomedir/oldstable 0.34.6-1 armhf
prometheus-homeplug-exporter/oldstable 0.3.0-2 armhf
python3-ofxhome/oldstable 0.3.3-3 all
r-cran-psychometric/oldstable 2.2-2 armhf
sweethome3d-furniture-editor/oldstable 1.25-1 all
sweethome3d-furniture-nonfree/oldstable 1.6.2-2 all
sweethome3d-furniture/oldstable 1.8-1 all
sweethome3d-textures-editor/oldstable 1.6-3 all
sweethome3d/oldstable 6.4.2+dfsg-2 all
unburden-home-dir-doc/oldstable 0.4.1.2 all
unburden-home-dir/oldstable 0.4.1.2 all
pi@homebridge:/usr/local/sbin $ sudo apt install homebridge
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package homebridge
pi@homebridge:/usr/local/sbin $ 
```

**Comment by ItsHaysus** [comment]
`sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.53.0`

worked for me, back to old version and everything is fine

**Comment by magnus319** [comment]
> > > Sadly `sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.53.0` doesn't resolve the issue. :(
> > 
> > 
> > It worked for me by just trying to reinstall 4.54.0
> 
> What exactly did you do? Like this: `sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.54.0`

yes but without the '@4.54.0' at the end since it auto installs latest version without that.

**Comment by nexusis7** [comment]
> So there isn't even a `homebridge` package in the apt repositories anymore.
> 
> ```
> pi@homebridge:/usr/local/sbin $ sudo apt update
> Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
> Get:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
> Get:3 http://archive.raspberrypi.org/debian buster/main armhf Packages [400 kB]
> Fetched 447 kB in 2s (192 kB/s)   
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> All packages are up to date.
> pi@homebridge:/usr/local/sbin $ sudo apt list | grep home
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> debian-edu-artwork-homeworld/oldstable 2.11.6-1 all
> golang-github-mitchellh-go-homedir-dev/oldstable 1.1.0-1 all
> hdhomerun-config/oldstable 20210210-1 armhf
> homebank-data/oldstable 5.5.2-1 all
> homebank/oldstable 5.5.2-1 armhf
> homer-api-mysql/oldstable 5.0.6+dfsg2-3.2 armhf
> homer-api-postgresql/oldstable 5.0.6+dfsg2-3.2 armhf
> homer-api/oldstable 5.0.6+dfsg2-3.2 armhf
> homesick/oldstable 1.1.6-3 all
> kodi-pvr-hdhomerun-dbg/oldoldstable 3.5.0-1~buster armhf
> kodi-pvr-hdhomerun/oldoldstable 3.5.0-1~buster armhf
> libfile-homedir-perl/oldstable 1.006-1 all
> libfile-save-home-perl/oldstable 0.11-1 all
> libhdhomerun-dev/oldstable 20210210-1 armhf
> libhdhomerun4/oldstable 20210210-1 armhf
> librust-home-dev/oldstable 0.5.1-1 armhf
> minetest-mod-homedecor/oldstable 20200604.1-1 all
> oddjob-mkhomedir/oldstable 0.34.6-1 armhf
> prometheus-homeplug-exporter/oldstable 0.3.0-2 armhf
> python3-ofxhome/oldstable 0.3.3-3 all
> r-cran-psychometric/oldstable 2.2-2 armhf
> sweethome3d-furniture-editor/oldstable 1.25-1 all
> sweethome3d-furniture-nonfree/oldstable 1.6.2-2 all
> sweethome3d-furniture/oldstable 1.8-1 all
> sweethome3d-textures-editor/oldstable 1.6-3 all
> sweethome3d/oldstable 6.4.2+dfsg-2 all
> unburden-home-dir-doc/oldstable 0.4.1.2 all
> unburden-home-dir/oldstable 0.4.1.2 all
> pi@homebridge:/usr/local/sbin $ sudo apt install homebridge
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package homebridge
> pi@homebridge:/usr/local/sbin $ 
> ```

interesting.. are they being bought out so big corpos can start charging? lol

**Comment by ivanvorobei** [comment]
Worked for me `sudo hb-config` via pi user.

<img width="567" alt="Screenshot 2023-12-07 at 23 31 46" src="https://github.com/homebridge/homebridge-config-ui-x/assets/10995774/5bed396d-ffec-4c76-b92e-884e44e6999a">

Choose update. if new version available it will solve problem. If not - reset, but you lose all data.

**Comment by kolorfilm** [comment]
> Worked for me `sudo hb-config` via pi user.
> 
> <img alt="Screenshot 2023-12-07 at 23 31 46" width="567" src="https://private-user-images.githubusercontent.com/10995774/288888544-5bed396d-ffec-4c76-b92e-884e44e6999a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODI0MzUsIm5iZiI6MTcwMTk4MjEzNSwicGF0aCI6Ii8xMDk5NTc3NC8yODg4ODg1NDQtNWJlZDM5NmQtZmZlYy00Yzc2LWI5MmUtODg0ZTQ0ZTY5OTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDIwNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYjBiNGJjZTBkMzQ3MmFjZTUzZDQ3Nzc0NDVkOWE2N2VlYjk4NjM4YjQ4MzhiZGY0NDc5MjU5NWI0MzM2ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lDB7yCOoDI0xdf4Oj2_ZojwWwlrLYt5HEPxhGqLaAa8">
> Choose update. if new version available it will solve problem. If not - reset, but you lose all data.

`sudo apt reinstall homebridge` should also do the trick. worked in my case.

**Comment by jonnyborbs** [comment]
There are two parallel problems here and I think I see the common thread emerging.

My hypothesis:
Folks who had recently updated their apt package lists may no longer have had a reference for the homebridge package.

The UI plugin update seems to have attempted an update/upgrade in place and removed the package, then was unable to find a new one to install and replace it.

Folks who had out of date apt package lists still had pointers to the now missing binaries and had a different set of problems.

**Comment by ivanvorobei** [comment]
> > Worked for me `sudo hb-config` via pi user.
> > <img alt="Screenshot 2023-12-07 at 23 31 46" width="567" src="https://private-user-images.githubusercontent.com/10995774/288888544-5bed396d-ffec-4c76-b92e-884e44e6999a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODI0MzUsIm5iZiI6MTcwMTk4MjEzNSwicGF0aCI6Ii8xMDk5NTc3NC8yODg4ODg1NDQtNWJlZDM5NmQtZmZlYy00Yzc2LWI5MmUtODg0ZTQ0ZTY5OTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDIwNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYjBiNGJjZTBkMzQ3MmFjZTUzZDQ3Nzc0NDVkOWE2N2VlYjk4NjM4YjQ4MzhiZGY0NDc5MjU5NWI0MzM2ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lDB7yCOoDI0xdf4Oj2_ZojwWwlrLYt5HEPxhGqLaAa8">
> > Choose update. if new version available it will solve problem. If not - reset, but you lose all data.
> 
> `sudo apt reinstall homebridge` should also do the trick. worked in my case.

its ask root access for me, I haven't password. but yes solution around it.

**Comment by Krillle** [comment]
> Worked for me `sudo hb-config` via pi user.
> 
> <img alt="Screenshot 2023-12-07 at 23 31 46" width="567" src="https://private-user-images.githubusercontent.com/10995774/288888544-5bed396d-ffec-4c76-b92e-884e44e6999a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODI3MDUsIm5iZiI6MTcwMTk4MjQwNSwicGF0aCI6Ii8xMDk5NTc3NC8yODg4ODg1NDQtNWJlZDM5NmQtZmZlYy00Yzc2LWI5MmUtODg0ZTQ0ZTY5OTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDIwNTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkM2IxYjY4MzQzMzRhOGVlNWYzMDMyNmI1NmY0ZGM3YzFkYTY5YzM3Mjc1MGZiY2Y5MTQ0NTBlZWFiYmQ4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YcXetUEqhjXXjWq1cYFoSXgMfgTBaotWglo8-AmYUIU">
> Choose update. if new version available it will solve problem. If not - reset, but you lose all data.

Worked for me. Thanks a lot!

**Comment by jonnyborbs** [comment]
> There are two parallel problems here and I think I see the common thread emerging.
> 
> My hypothesis: Folks who had recently updated their apt package lists may no longer have had a reference for the homebridge package.
> 
> The UI plugin update seems to have attempted an update/upgrade in place and removed the package, then was unable to find a new one to install and replace it.
> 
> Folks who had out of date apt package lists still had pointers to the now missing binaries and had a different set of problems.

Problem now is, how do we get that package back. There is so little information on homebridge core given that the wiki is completely broken @oznu hate to tag by name but wonder if you have thoughts here.

**Comment by rcoletti116** [comment]
@bwp91 @mkz212 for visibility

**Comment by testpaul999** [comment]
LOL it is so easy.
Look at the byte what the package have
4.53
![IMG_4382](https://github.com/homebridge/homebridge-config-ui-x/assets/35597907/d5b87195-1fd3-44c9-b37d-85a2752a638c)
23mb
4.54
![IMG_4381](https://github.com/homebridge/homebridge-config-ui-x/assets/35597907/e86b1f33-1f05-438a-8dc7-11e6d43585e2)
378bytes
In this are only a sym-link ….😂

**Comment by Marco-Erlangen** [comment]
Would also explain why the update only takes 1 second :-)

**Comment by noelhibbard** [comment]
> There are two parallel problems here and I think I see the common thread emerging.
> 
> My hypothesis: Folks who had recently updated their apt package lists may no longer have had a reference for the homebridge package.
> 
> The UI plugin update seems to have attempted an update/upgrade in place and removed the package, then was unable to find a new one to install and replace it.
> 
> Folks who had out of date apt package lists still had pointers to the now missing binaries and had a different set of problems.

I think it's something else because the docker image doesn't use apt and it also died.

**Comment by jonnyborbs** [comment]
So running `sudo npm uninstall -g homebridge-config-ui-x`

Followed by `sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.53.0`

brought the whole service back online, however there is still no `hb-config` binary on the system.

**Comment by brianld75** [comment]
`sudo apt reinstall homebridge` brought back the web UI for me, but now my entire Homebridge setup, plugins, devices, etc. is all gone.

**Comment by sdflyguy** [comment]
> Same here, running in Docker , did a "Re deploy" in Portainer and everything came back as it was before (Only needed to update Node)

Can confirm. Using Portainer, a simple "recreate" and also re-pulling the image within the Homebridge container brought me back to the previous version. All plug-ins and config remained intact. Just had to update node again.

**Comment by ItsHaysus** [comment]
> So running `sudo npm uninstall -g homebridge-config-ui-x`
> 
> Followed by `sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.53.0`
> 
> brought the whole service back online, however there is still no `hb-config` binary on the system.

yes i did this but no hb-config either

**Comment by jonnyborbs** [comment]
> > There are two parallel problems here and I think I see the common thread emerging.
> > My hypothesis: Folks who had recently updated their apt package lists may no longer have had a reference for the homebridge package.
> > The UI plugin update seems to have attempted an update/upgrade in place and removed the package, then was unable to find a new one to install and replace it.
> > Folks who had out of date apt package lists still had pointers to the now missing binaries and had a different set of problems.
> 
> I think it's something else because the docker image doesn't use apt and it also died.

Yeah, you may be right. There are a lot of problems coming together at once here. Thanks for reporting though, hypotheses are meant to evolve when new data is presented!

**Comment by jonnyborbs** [comment]
The hb-config issue is so strange. That is a local binary, not a node package as far as I can tell. Where did it go? And why is there no homebridge package in the apt repositories anymore?

**Comment by Gobias64** [comment]
> Worked for me `sudo hb-config` via pi user.
> 
> <img alt="Screenshot 2023-12-07 at 23 31 46" width="567" src="https://private-user-images.githubusercontent.com/10995774/288888544-5bed396d-ffec-4c76-b92e-884e44e6999a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODI5MzQsIm5iZiI6MTcwMTk4MjYzNCwicGF0aCI6Ii8xMDk5NTc3NC8yODg4ODg1NDQtNWJlZDM5NmQtZmZlYy00Yzc2LWI5MmUtODg0ZTQ0ZTY5OTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDIwNTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjI4MjJlMjM1NmY0ZTZiNWJlNDFiZjk5N2VlZWYxYzUyOWNlOGIyODBhNzJlNjNhZTZjMzdiYzZhYzdkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KKlyacgHHeXLWkizycKJQEMcJbnCmAzdl3ZuOw1t8wc">
> Choose update. if new version available it will solve problem. If not - reset, but you lose all data.

I tried this, but when I try to access Homebridge UI, it's still stuck saying Homebridge is "starting now"

Also, I'm still getting an error saying that hb-service is not found.

**Comment by rasmus050504** [comment]
sudo apt reinstall homebridge 
brought some kind of HB back in running state.
Old HB, old Node.js, and I can not update anythin without HB crashing again. All my dummy switches ended in default room, and I have no devices from Zigbee2MQTT! My home automation is kind of f...ed now

**Comment by aspaviento** [comment]
What a disaster of 'Update available' (with the irony in the update text with a 'happy holidays'... yes I started to imagine to invest all my holidays restoring this ...): hb-service just gone, homebridge stopped working, everything gone.
 
To go back to the previous version (and your running configuration):

sudo npm -g install homebridge-config-ui-x@4.53.0
 
AVOID reinstall since you will lose your plugins and configuration.

Please somebody to rollback this update and make it working again. Big thanks to the homebridge team for the hard work of providing us new updates, but please be careful ...

**Comment by guillochon** [comment]
> So running `sudo npm uninstall -g homebridge-config-ui-x`
> 
> Followed by `sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.53.0`
> 
> brought the whole service back online, however there is still no `hb-config` binary on the system.

This particular solution worked for me, however I didn't have the full nuclear "all the binaries are gone" thing happen to me. I'd recommend anyone troubleshooting this to ssh into their homebridge first and check if their `hb-config` still exists before running the above.

**Comment by nexusis7** [comment]
> > Same here, running in Docker , did a "Re deploy" in Portainer and everything came back as it was before (Only needed to update Node)
> 
> Can confirm. Using Portainer, a simple "recreate" and also re-pulling the image within the Homebridge container brought me back to the previous version. All plug-ins and config remained intact. Just had to update node again.

had to do the same with portainer. had to restore from backup. New node 20.* broke some of my plugins

**Comment by bL4zZ95** [comment]
> `sudo apt reinstall homebridge` works on Raspberry Pi 👍

Thanks that works for me too.

**Comment by mnemo70** [comment]
Seems like v4.54.0 has been re-released with the correct size.

![image](https://github.com/homebridge/homebridge-config-ui-x/assets/30214405/f74b003f-c9a2-462c-a67c-eb82a5edcaa8)

**Comment by jonnyborbs** [comment]
I see someone created a fork issue from this for `hb-config` explicitly - I wonder if this was just a part of the rather sweeping component rearchitecture intended in 4.54.0 but it was not documented in the changelog if so.

https://github.com/homebridge/homebridge-config-ui-x/issues/1913

@bwp91 @donavanbecker @jsiegenthaler just CCing you in since git blame on the changelog sent me your way 😄

**Comment by jonnyborbs** [comment]
> Seems like v4.54.0 has been re-released with the correct size.
> 
> ![image](https://private-user-images.githubusercontent.com/30214405/288896661-f74b003f-c9a2-462c-a67c-eb82a5edcaa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODQ2NDIsIm5iZiI6MTcwMTk4NDM0MiwicGF0aCI6Ii8zMDIxNDQwNS8yODg4OTY2NjEtZjc0YjAwM2YtYzlhMi00NjJjLWE2N2MtZWI4MmE1ZWRjYWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDIxMjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczOGNhYjgwODkzZTU4YTdiNTllMWM1ZTMzMmM0Mjg0Mjk0MGNkZGQ1YmRjNTBmMmU2ZTA1MGQ3NzJjMGI3MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uZlXIdJkmRpYuNumoynLFTrI_1grQFRtPC1hHOpfdac)

lol, someone other than me can try this out and report back. I've had my fill of excitement for the day 😂

**Comment by mnemo70** [comment]
I just did `sudo npm -g install homebridge-config-ui-x` and it works. Yay!

![image](https://github.com/homebridge/homebridge-config-ui-x/assets/30214405/7d31f6e9-bac4-45cb-8fc2-b014db9a6ea4)

**Comment by brianld75** [comment]
> > Seems like v4.54.0 has been re-released with the correct size.
> > ![image](https://private-user-images.githubusercontent.com/30214405/288896661-f74b003f-c9a2-462c-a67c-eb82a5edcaa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODQ2NDIsIm5iZiI6MTcwMTk4NDM0MiwicGF0aCI6Ii8zMDIxNDQwNS8yODg4OTY2NjEtZjc0YjAwM2YtYzlhMi00NjJjLWE2N2MtZWI4MmE1ZWRjYWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDIxMjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczOGNhYjgwODkzZTU4YTdiNTllMWM1ZTMzMmM0Mjg0Mjk0MGNkZGQ1YmRjNTBmMmU2ZTA1MGQ3NzJjMGI3MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uZlXIdJkmRpYuNumoynLFTrI_1grQFRtPC1hHOpfdac)
> 
> lol, someone other than me can try this out and report back. I've had my fill of excitement for the day 😂

I just tried it ... works!

**Comment by woeperbe** [comment]
Here also everything is messed up running on ubuntu server 20
Had to restore the virtual machine completely

**Comment by buzz-dee81** [comment]
> `sudo apt reinstall homebridge` works on Raspberry Pi 👍

Did NOT work for me, reinstall failed with missing files / broken pipe.

had to `sudo apt purge homebridge`

and `sudo apt install homebridge`

make sure to copy you local backups before you do so as the `purge` will remove your data directories entirely (in my case it was under /var/lib/homebridge/backups/instance-backups )

after the install I restored from the backup file and had all running again within 5 min.

**Comment by kolorfilm** [comment]
I tried to update again from the ui and it worked for me as well! finally merry christmas! 🤣

**Comment by town3r** [comment]
Ugh I still get `Unable to locate package homebridge` even with the `purge` command.

**Comment by jonnyborbs** [comment]
> Ugh I still get `Unable to locate package homebridge` even with the `purge` command.

if you have a recently updated package list, it simply is not there. where it went is another issue, I do not know.

**Comment by gleschnapi** [comment]
> Possible solution
> 
> * download version 4.53.0 from GitHub
> * Remove link who found at  /usr/local/lib/node_modules/homebridge-config-ui-x/
> * Extract the tar.gz and copy the part homebridge-config-ui-x to /usr/local/lib/node_modules/
> * For me all run fine now at the old version

this worked fine for me as well, thanks!!

**Comment by jonnyborbs** [comment]
Can now confirm that 4.54.0 installs properly from either the npm cli or the web UI if you did manage to get it working again.

Still no idea what the fate of `hb-config` as a command line utility was
Still no idea why there is no longer a `homebridge` package in apt

Things do work again, however. For me, YMMV it seems!

**Comment by jeanchrijaz** [comment]
> I just did `sudo npm -g install homebridge-config-ui-x` and it works. Yay!
> 
this worked fine for me too 👍

**Comment by adavison007** [comment]
> > I just did `sudo npm -g install homebridge-config-ui-x` and it works. Yay!
> 
> this worked fine for me too 👍

Did it fix HB-Config?

**Comment by jonnyborbs** [comment]
> > > I just did `sudo npm -g install homebridge-config-ui-x` and it works. Yay!
> 
> > 
> 
> > this worked fine for me too 👍
> 
> 
> 
> Did it fix HB-Config?
> 
> 

Nope, see my post above.

**Comment by nexusis7** [comment]
updated works now.

**Comment by rcoletti116** [comment]
Seems my problems are not so easily solved. The package is missing on mine and my attempts to fix are causing more complications. I have my backup files so may to save those and re-image.

**Comment by yogeshlonkar** [comment]
`hb-config` was missing for me as well, I'm using official homebridge-raspbian-image.

I was not able to reinstall homebridge via apt, but I copied https://github.com/homebridge/homebridge-raspbian-image/blob/latest/stage3_homebridge/01-homebridge/files/hb-config-new to `/usr/local/sbin/` and ran update homebridge. From whatever state my instance was in, now it was back to working again.

Then I updated plugin again from UI and it's still working for me after update so looks like problem is fixed.

**Comment by jonnyborbs** [comment]
I still have a suspicion that the hb-config utility was removed intentionally, since the UI now allows you to do NPM and server upgrades directly from it. But this was not made explicit, and I think is adding to a lot of our confusion. I hope we can get a maintainer to weigh in here and tell us for sure.

For what it's worth, if this was intentional, I believe it was misguided. When the UI is not working, that utility is a lifesaver for manual intervention tasks.

**Comment by pandizajner** [comment]
I agree. The `hb-config` just saved me. After a long story of trying to put the service working back... I've run reinstallation of the `homebridge-config-ui-x@4.53.0` and used `hb-config` with option 2 to update Homebridge. It didn't bump the version of UI, so I'm still 4.53.0 and the waiting update is there. 

Btw. What's interesting, there's alrady 4.53.1 beta available. Anybody checked that? 
<img width="516" alt="image" src="https://github.com/homebridge/homebridge-config-ui-x/assets/1434834/47d6bc62-4a5b-400a-a0c1-342bab4583c9">

**Comment by nexusis7** [comment]
the option to make a child plugin has disappeared

**Comment by jonnyborbs** [comment]
> the option to make a child plugin has disappeared

This is probably a separate issue

**Comment by Gobias64** [comment]
> I just did `sudo npm -g install homebridge-config-ui-x` and it works. Yay!
> 
> ![image](https://private-user-images.githubusercontent.com/30214405/288897372-7d31f6e9-bac4-45cb-8fc2-b014db9a6ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODc4ODQsIm5iZiI6MTcwMTk4NzU4NCwicGF0aCI6Ii8zMDIxNDQwNS8yODg4OTczNzItN2QzMWY2ZTktYmFjNC00NWNiLThmYzItYjAxNGRiOWE2ZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDIyMTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MGM4MGU3NWM3NGM1OWVkZDFlODg0MTJmOGUxMTZjNzYzMDUxOTk1OTMyMzYwZDIzNzg2Njc1MTQzNjY0MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fuJBOg48dCXBY2FCcePBLSSNZqZ0G-2OoV7m6e0XsCc)

Worked for me, too! Thanks!

**Comment by databoy01** [comment]
This is the fix if you’re using raspberry pi

terminal into the pi using name :pi and password: raspberry once in 

sudo apt reinstall homebridge

then 

sudo reboot

**Comment by jonnyborbs** [comment]
> This is the fix if you’re using raspberry pi
> 
> 
> 
> terminal into the pi using name :pi and password: raspberry once in 
> 
> 
> 
> sudo apt reinstall homebridge
> 
> 
> 
> then 
> 
> 
> 
> sudo reboot

As discussed many times, this is not a silver bullet. The package is not available in the current iteration of the buster or bullseye apt repositories and these commands do not succeed. 

Still hoping we can find out why that is the case.

**Comment by databoy01** [comment]
> > This is the fix if you’re using raspberry pi
> > terminal into the pi using name :pi and password: raspberry once in
> > sudo apt reinstall homebridge
> > then
> > sudo reboot
> 
> As discussed many times, this is not a silver bullet. The package is not available in the current iteration of the buster or bullseye apt repositories and these commands do not succeed.
> 
> Still hoping we can find out why that is the case.

I’m saying it fixes mine back to how my homebridge was running before update and now again shows I should update to the version that kills my homebridge….

might not be the silver bullet as you say, but it gets it working like it was before update so I would consider that even better than how it behaved after the update.

**Comment by rasmus050504** [comment]
So I had to do the purge / install / restore backup, and I have a working HB.
However all my automation in Apple Home which includes devices from HB (Dummy switches, Zigbee2MQTT devices) are corrupted, and have to be rebuild.
This was the last time I did an update of HB unless it becomes strictly necessary!

**Comment by ghost-ps** [comment]
> the option to make a child plugin has disappeared

I can't confirm that! 

Only if the child plugin meant a child bridge …

![IMG_1610](https://github.com/homebridge/homebridge-config-ui-x/assets/87266062/9740ace3-c8ff-4238-a039-9c43fd4f7d88)

**Comment by mnemo70** [comment]
> This is the fix if you’re using raspberry pi
> 
> terminal into the pi using name :pi and password: raspberry once in
> 
> sudo apt reinstall homebridge
> 
> then
> 
> sudo reboot

That is like rebuilding the complete house (Homebridge) when the satellite dish (the Homebridge UI) is misadjusted.

**Comment by Madcat-76310** [comment]
> I just did `sudo npm -g install homebridge-config-ui-x` and it works. Yay!
> 
> ![image](https://private-user-images.githubusercontent.com/30214405/288897372-7d31f6e9-bac4-45cb-8fc2-b014db9a6ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzIwNTksIm5iZiI6MTcwMjAzMTc1OSwicGF0aCI6Ii8zMDIxNDQwNS8yODg4OTczNzItN2QzMWY2ZTktYmFjNC00NWNiLThmYzItYjAxNGRiOWE2ZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDEwMzU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhM2RkZjgyYjYyMzUzYjA5NGI1NzA5NTlmYTYyMTUzMDBiZDE0ZDJmYjk2ZGFmNzhhZTRmYzU2YmI1MDdjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.66toQDFybkFUKY4_0y98HxkfqPtQvxAlnLpfRfqIAMA)

Worked for me too !

(use a backup on a Freebox Delta Virtual Machine too)

**Comment by Staubgeborener** [comment]
> Do not attach artifacts to GitHub releases if the tarball is smaller than 10MB

(Source: https://github.com/homebridge/homebridge-config-ui-x/releases/tag/4.54.1)
I think we can close this one.

**Comment by jonnyborbs** [comment]
Can we get some answers on the fate of `hb-config` before we do that @Staubgeborener? We are all looking for it and confused by its absence 😄

**Comment by nexusis7** [comment]
> > the option to make a child plugin has disappeared
> 
> I can't confirm that!
> 
> Only if the child plugin meant a child bridge …
> 
> ![IMG_1610](https://private-user-images.githubusercontent.com/87266062/288999677-9740ace3-c8ff-4238-a039-9c43fd4f7d88.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNTg3ODMsIm5iZiI6MTcwMjA1ODQ4MywicGF0aCI6Ii84NzI2NjA2Mi8yODg5OTk2NzctOTc0MGFjZTMtYzhmZi00MjM4LWEwMzktOWM0M2ZkNGY3ZDg4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOFQxODAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTIyOWI2NDIxYjc3M2E3YTQ1NDQxZWM3ZWI0ZTFmZjlhOTVlOTI3OGE3ZDc4ZmYwZDExMTcxYjQzNDZjYjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8tKV26dgcKfzdIE3t7O8A-5N4cWnhcggRRANzW9OYE4)

it didnt give me that option although the plugin used to be a child. I had to modify the config manually to add the child code.

**Comment by mkz212** [comment]
Fixed in 4.54.1. Issue can be closed.

**Comment by jonnyborbs** [comment]
> Can we get some answers on the fate of `hb-config` before we do that @Staubgeborener? We are all looking for it and confused by its absence 😄

Again, would love to learn more here first @mkz212 -  everyone is scanning right past this very important and reasonable question. Are we moving to an entirely web UI based config mechanism? This feels like a mistake if so, and would love to learn more.

**Comment by mkz212** [comment]
> > Can we get some answers on the fate of `hb-config` before we do that @Staubgeborener? We are all looking for it and confused by its absence 😄
> 
> Again, would love to learn more here first @mkz212 - everyone is scanning right past this very important and reasonable question. Are we moving to an entirely web UI based config mechanism? This feels like a mistake if so, and would love to learn more.

I don't know that. This is a question for creators / administrators. I meant that an error with the lack of the child bridge button was fixed, the update file was fixed and a security was added so that such a situation would not happen again.

**Comment by nexusis7** [comment]
> > > Can we get some answers on the fate of `hb-config` before we do that @Staubgeborener? We are all looking for it and confused by its absence 😄
> > 
> > 
> > Again, would love to learn more here first @mkz212 - everyone is scanning right past this very important and reasonable question. Are we moving to an entirely web UI based config mechanism? This feels like a mistake if so, and would love to learn more.
> 
> I don't know that. This is a question for creators / administrators. I meant that an error with the lack of the child bridge button was fixed, the update file was fixed and a security was added so that such a situation would not happen again.

Thank you Sir!

**Comment by bwp91** [comment]
Hi all, quick stuff first:

> the option to make a child plugin has disappeared

fixed in 4.54.1 (for some users the option would not show in the menu)

> I still have a suspicion that the hb-config utility was removed intentionally, since the UI now allows you to do NPM and server upgrades directly from it.

this is not the case :)  this discussion is in https://github.com/homebridge/homebridge-config-ui-x/issues/1913

---

just prepping some info about yesterdays release...

**Comment by jonnyborbs** [comment]
> Hi all, quick stuff first:
> 
> > the option to make a child plugin has disappeared
> 
> fixed in 4.54.1 (for some users the option would not show in the menu)
> 
> > I still have a suspicion that the hb-config utility was removed intentionally, since the UI now allows you to do NPM and server upgrades directly from it.
> 
> this is not the case :) this discussion is in #1913
> 
> just prepping some info about yesterdays release...

Roger that, thanks so much. The discussion over in that issue is productive as well and moving forward. Appreciate all the help and hard work!

**Comment by vmcilwain** [comment]
> I just did `sudo npm -g install homebridge-config-ui-x` and it works. Yay!
> 
> 
> 
> ![image](https://github.com/homebridge/homebridge-config-ui-x/assets/30214405/7d31f6e9-bac4-45cb-8fc2-b014db9a6ea4)
> 
> 

What directory did you run this command? I want to make sure I try this in the right place. 

Thanks

**Comment by mnemo70** [comment]
> What directory did you run this command? I want to make sure I try this in the right place.

Not important because it's a "global" install, indicated by the -g parameter.
