### ISSUE TITLE
HB-Config No longer works after latest update

### ISSUE THREAD

**Issue by adavison007** [oznu/homebridge-config-ui-x#1913]
### Describe The Bug

HB-Config No longer works after latest update - Nothing happens when typing this command in via SSH

### Homebridge UI Version

Latest

### Homebridge Version

Latest

### Node.js Version

Latest

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by JurgenLB** [comment]
See discussion in #1912 
Kind regards

**Comment by town3r** [comment]
I'm also still experiencing this issue.

Was able to get homebridge-config-ui-x working again and the web UI is up and running.

But the `sudo hb-config` command no longer works.

Nothing happens after hitting return.

Super don't want to nuke my whole setup

**Comment by jonnyborbs** [comment]
We can also move discussion of `hb-config` here @Staubgeborener

**Comment by bwp91** [comment]
Hi all, there have been no changes to hb-config in the 4.54.x versions, and there are no plans to remove it.

It's likely that if you tried to update to 4.54.0 within the first hour or so after its release, then the hb-config service was deleted. A reinstall of homebridge-config-ui-x should get this working again.

**Comment by jonnyborbs** [comment]
> Hi all, there have been no changes to hb-config in the 4.54.x versions, and there are no plans to remove it.
> 
> It's likely that if you tried to update to 4.54.0 within the first hour or so after its release, then the hb-config service was deleted. A reinstall of homebridge-config-ui-x should get this working again.

That doesn't seem to be true - I've reinstalled (as have dozens of my friends in that other issue) and the binary is still a 1 byte, empty file.

**Comment by jonnyborbs** [comment]
![CleanShot 2023-12-08 at 10 15 46](https://github.com/homebridge/homebridge-config-ui-x/assets/25127543/e5a58cdd-be6c-424f-abfe-932e68ec6425)

See attached

**Comment by NorthernMan54** [comment]
@jonnyborbs 

Mine is 

28K -rwxr-xr-x 1 root root 26K Nov 28 13:18 /usr/local/sbin/hb-config

That particular file is not part of home bridge-config-ui-x, and is only part of the homebridge-raspbian-image

**Comment by NorthernMan54** [comment]
The original file is here - https://github.com/homebridge/homebridge-raspbian-image/tree/latest/stage3_homebridge/01-homebridge/files

The one hb-config-new is the current version, and hb-config is a legacy version

**Comment by jonnyborbs** [comment]
Interesting. The fact remains that it was there before this plugin upgrade and is gone now though...

**Comment by NorthernMan54** [comment]
@jonnyborbs Looking at your screen shot, that file was last updated on `Dec 2 @ 17:11` local time.  Am thinking it has been borked since then.  Do you recall making any changes then ?

**Comment by JurgenLB** [comment]
> The original file is here - https://github.com/homebridge/homebridge-raspbian-image/tree/latest/stage3_homebridge/01-homebridge/files
> 
> The one hb-config-new is the current version, and hb-config is a legacy version

@NorthernMan54 in that image the file hb-config is `0 lines (0 loc) · 1 Byte`
![image](https://github.com/homebridge/homebridge-config-ui-x/assets/77586573/d939976d-63df-4cc4-b203-fb2d41f96757)

**Comment by jonnyborbs** [comment]
> @jonnyborbs Looking at your screen shot, that file was last updated on `Dec 2 @ 17:11` local time. Am thinking it has been borked since then. Do you recall making any changes then ?

I don't remember doing anything there, no. I haven't logged directly into the box in ages before the trouble yesterday

**Comment by jonnyborbs** [comment]
I also wasn't the only one for whom the file vanished after the UI plugin upgrade yesterday, there were loads of reports of the same

**Comment by town3r** [comment]
What commands should we run in order to restore hb-config with those files?

**Comment by jonnyborbs** [comment]
@adavison007 I think you might have mistakenly marked this as closed, could you reopen?

**Comment by adavison007** [comment]
Mine also stopped working after the UI update yesterday.... no error when running, nothing simply happens after typing the command in.

**Comment by adavison007** [comment]
I closed this chat as completed by accident somehow, how do I change that back?

**Comment by adavison007** [comment]
> @adavison007 I think you might have mistakenly marked this as closed, could you reopen?

How

**Comment by jonnyborbs** [comment]
You got it :)

**Comment by adavison007** [comment]
> What commands should we run in order to restore hb-config with those files?

That would be good to know

**Comment by jonnyborbs** [comment]
I am wondering if this is a packaging and release issue based on the repo you linked @NorthernMan54 - since the `hb-config` file in that commit is indeed empty, I wonder if the `hb-config-new` version was not included in the releases.

**Comment by NorthernMan54** [comment]
@jonnyborbs Looking at forensically for a second, what does these commands show on your system ?

pi@homebridge:~ $ ls -lc /usr/local/sbin/hb-config 
-rwxr-xr-x 1 root root 26145 Nov 28 13:21 /usr/local/sbin/hb-config
pi@homebridge:~ $ ls -l /usr/local/sbin/hb-config 
-rwxr-xr-x 1 root root 26145 Nov 28 13:18 /usr/local/sbin/hb-config

My understanding is that the repository / package is only used when a new homebridge raspbian image is installed onto a SD card, and not used by homebridge-config-ui-x.  But we need to look further into why / how the file was truncated

**Comment by jonnyborbs** [comment]
If you are in an emergency situation and need the file back immediately:

1. Log in to your console
2. run `sudo wget https://raw.githubusercontent.com/homebridge/homebridge-raspbian-image/latest/stage3_homebridge/01-homebridge/files/hb-config-new -O /usr/local/sbin/hb-config-new ; sudo chmod +x /usr/local/sbin/hb-config-new`
3. You can then run `sudo hb-config-new` to access the utility
4. Selecting option 8 will update the original file. Do this and exit the utility
5. Run `sudo rm /usr/local/sbin/hb-config-new`
6. You should now have the config utility back as expected

But I still think this is something that should be corrected in a packaged release and not via this method

**Comment by jonnyborbs** [comment]
@NorthernMan54 here you go
![CleanShot 2023-12-08 at 11 01 55](https://github.com/homebridge/homebridge-config-ui-x/assets/25127543/6ccecb3f-9fa4-46ef-94ac-7a18fb874eb1)

**Comment by NorthernMan54** [comment]
Humm, still shows Dec 2nd

What about 

```
pi@homebridge:~ $ ls -l /etc/hb-release 
-rw-r--r-- 1 root root 56 Nov 28 13:18 /etc/hb-release
pi@homebridge:~ $ cat /etc/hb-release
"homebridge/homebridge-raspbian-image-v1.1.2-\(64bit\)"
```

That is the build image for your homebridge-raspbian image

**Comment by town3r** [comment]
> If you are in an emergency situation and need the file back immediately:
> 
> 
> 
> 1. Log in to your console
> 
> 2. run `sudo wget https://raw.githubusercontent.com/homebridge/homebridge-raspbian-image/latest/stage3_homebridge/01-homebridge/files/hb-config-new -O=/usr/local/sbin/hb-config-new ; sudo chmod +x /usr/local/sbin/hb-config-new`
> 
> 3. You can then run `sudo hb-config-new` to access the utility
> 
> 
> 
> But I still think this is something that should be corrected in a packaged release and not via this method, which is why I did not replace the existing file in situ

I'm getting this:

![image](https://github.com/homebridge/homebridge-config-ui-x/assets/12396203/2c1e7d9b-38df-41b9-ac7a-89b2f91ccc23)

**Comment by jonnyborbs** [comment]
> > If you are in an emergency situation and need the file back immediately:
> > 
> > 1. Log in to your console
> > 2. run `sudo wget https://raw.githubusercontent.com/homebridge/homebridge-raspbian-image/latest/stage3_homebridge/01-homebridge/files/hb-config-new -O=/usr/local/sbin/hb-config-new ; sudo chmod +x /usr/local/sbin/hb-config-new`
> > 3. You can then run `sudo hb-config-new` to access the utility
> > 
> > But I still think this is something that should be corrected in a packaged release and not via this method, which is why I did not replace the existing file in situ
> 
> I'm getting this:
> 
> ![image](https://private-user-images.githubusercontent.com/12396203/289164580-2c1e7d9b-38df-41b9-ac7a-89b2f91ccc23.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNjI2NjgsIm5iZiI6MTcwMjA2MjM2OCwicGF0aCI6Ii8xMjM5NjIwMy8yODkxNjQ1ODAtMmMxZTdkOWItMzhkZi00MWI5LWFjN2EtODliMmY5MWNjYzIzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOFQxOTA2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2EwOTJhMDZkMTdlZDYyYTE0OGQxNmVhZGUxODVhNWI3N2Y3MGFiZjA2N2YwYTEzNzRkMWNhNTQzNzVmYWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-oTRiJoTX66XDjBz5WQ-mfs07FO78czVNiNCwWvV-xE)

Sorry mate I had a typo. I updated the command above

**Comment by jonnyborbs** [comment]
> Humm, still shows Dec 2nd
> 
> What about
> 
> ```
> pi@homebridge:~ $ ls -l /etc/hb-release 
> -rw-r--r-- 1 root root 56 Nov 28 13:18 /etc/hb-release
> pi@homebridge:~ $ cat /etc/hb-release
> "homebridge/homebridge-raspbian-image-v1.1.2-\(64bit\)"
> ```
> 
> That is the build image for your homebridge-raspbian image

Here you go again, v different than yours but that is to be expected I think
![CleanShot 2023-12-08 at 11 09 02](https://github.com/homebridge/homebridge-config-ui-x/assets/25127543/8af0f7c0-2357-4a57-9848-a364194ddaa4)

July 2020 sounds about right for when I would have imaged this initially and it's been upgraded in place ever since.

**Comment by jonnyborbs** [comment]
~There's also this potentially related anomaly I reported: https://github.com/homebridge/homebridge-apt-pkg/issues/21~

This is probably unrelated. I am zeroing in on pre- or post- install scripts in the UI package

**Comment by jonnyborbs** [comment]
As a side note: I ran the `hb-config-new` file which I retrieved from the latest commit, and used option 8 - the `update this tool..` option, and it retrieved the file from GitHub and replaced the original `hb-config` file as expected.

So I still really think there is some pre- or post- install script that is not properly instantiating the new version as part of the UI package upgrades.

**Comment by town3r** [comment]
@jonnyborbs Thank you!
hb-config is back up and running.

**Comment by NorthernMan54** [comment]
@jonnyborbs Spent the last while digging thru things, and not seeing a trigger, I even went so far as to grab your version from 2020 and looked for a trigger.  Did you see anything ?

**Comment by jonnyborbs** [comment]
> @jonnyborbs Spent the last while digging thru things, and not seeing a trigger, I even went so far as to grab your version from 2020 and looked for a trigger. Did you see anything ?

Sorry, I'm not clear what you mean by trigger here. Do you mean an event that could have triggered the update? Only thing I can think of is I had to shut the RPi down for the first time in ages due to some electrical work I was doing around that time.

**Comment by NorthernMan54** [comment]
I was looking for a trigger in the code, that would cause hb-config to be erased / truncated

What date / time do you have for these ?

pi@homebridge:~ $ ls -l /etc/update-motd.d/*
-rwxr-xr-x 1 root root   23 Apr  4  2017 /etc/update-motd.d/10-uname
-rwxr-xr-x 1 root root  353 Nov 28 13:18 /etc/update-motd.d/15-linux
-rwxr-xr-x 1 root root 1532 Nov 28 13:18 /etc/update-motd.d/20-homebridge

**Comment by adavison007** [comment]
> @jonnyborbs Thank you! hb-config is back up and running.

What commands did you do to make this happen and did it affect the system running without a rebuild of config?

**Comment by jonnyborbs** [comment]
> I was looking for a trigger in the code, that would cause hb-config to be erased / truncated
> 
> What date / time do you have for these ?
> 
> pi@homebridge:~ $ ls -l /etc/update-motd.d/* -rwxr-xr-x 1 root root 23 Apr 4 2017 /etc/update-motd.d/10-uname -rwxr-xr-x 1 root root 353 Nov 28 13:18 /etc/update-motd.d/15-linux -rwxr-xr-x 1 root root 1532 Nov 28 13:18 /etc/update-motd.d/20-homebridge

![CleanShot 2023-12-08 at 11 51 10](https://github.com/homebridge/homebridge-config-ui-x/assets/25127543/f030471c-98b4-4353-a688-e215bb7fc33c)

**Comment by jonnyborbs** [comment]
> > @jonnyborbs Thank you! hb-config is back up and running.
> 
> What commands did you do to make this happen and did it affect the system running without a rebuild of config?

Scroll up a bit, I posted a step by step

**Comment by adavison007** [comment]
> > > @jonnyborbs Thank you! hb-config is back up and running.
> > 
> > 
> > What commands did you do to make this happen and did it affect the system running without a rebuild of config?
> 
> Scroll up a bit, I posted a step by step

This? sudo wget https://raw.githubusercontent.com/homebridge/homebridge-raspbian-image/latest/stage3_homebridge/01-homebridge/files/hb-config-new -O=/usr/local/sbin/hb-config-new ; sudo chmod +x /usr/local/sbin/hb-config-new

**Comment by NorthernMan54** [comment]
@jonnyborbs What is in the unattended-upgrades file ?

**Comment by jonnyborbs** [comment]
> > > > @jonnyborbs Thank you! hb-config is back up and running.
> > > 
> > > 
> > > What commands did you do to make this happen and did it affect the system running without a rebuild of config?
> > 
> > 
> > Scroll up a bit, I posted a step by step
> 
> This? sudo wget https://raw.githubusercontent.com/homebridge/homebridge-raspbian-image/latest/stage3_homebridge/01-homebridge/files/hb-config-new -O=/usr/local/sbin/hb-config-new ; sudo chmod +x /usr/local/sbin/hb-config-new

Keep scrolling. That is one step and that version has a typo in it.

**Comment by adavison007** [comment]
> > > > > @jonnyborbs Thank you! hb-config is back up and running.
> > > > 
> > > > 
> > > > What commands did you do to make this happen and did it affect the system running without a rebuild of config?
> > > 
> > > 
> > > Scroll up a bit, I posted a step by step
> > 
> > 
> > This? sudo wget https://raw.githubusercontent.com/homebridge/homebridge-raspbian-image/latest/stage3_homebridge/01-homebridge/files/hb-config-new -O=/usr/local/sbin/hb-config-new ; sudo chmod +x /usr/local/sbin/hb-config-new
> 
> Keep scrolling. That is one step and that version has a typo in it.

Don't worry, I'm too scared at trying if I have to pull it together, if you have a moment it would be good for all steps and commands on this response. It would be highly appreciated

**Comment by jonnyborbs** [comment]
> @jonnyborbs What is in the unattended-upgrades file ?

It's boring...
![CleanShot 2023-12-08 at 11 55 13](https://github.com/homebridge/homebridge-config-ui-x/assets/25127543/1b54f8e3-e364-42e2-a064-2c797fc5fef8)

**Comment by jonnyborbs** [comment]
> > > > > > @jonnyborbs Thank you! hb-config is back up and running.
> > > > > 
> > > > > 
> > > > > What commands did you do to make this happen and did it affect the system running without a rebuild of config?
> > > > 
> > > > 
> > > > Scroll up a bit, I posted a step by step
> > > 
> > > 
> > > This? sudo wget https://raw.githubusercontent.com/homebridge/homebridge-raspbian-image/latest/stage3_homebridge/01-homebridge/files/hb-config-new -O=/usr/local/sbin/hb-config-new ; sudo chmod +x /usr/local/sbin/hb-config-new
> > 
> > 
> > Keep scrolling. That is one step and that version has a typo in it.
> 
> Don't worry, I'm too scared at trying if I have to pull it together, if you have a moment it would be good for all steps and commands on this response. It would be highly appreciated

I already did. Keep scrolling.

https://github.com/homebridge/homebridge-config-ui-x/issues/1913#issuecomment-1847676218

**Comment by adavison007** [comment]
> > > > > > > @jonnyborbs Thank you! hb-config is back up and running.
> > > > > > 
> > > > > > 
> > > > > > What commands did you do to make this happen and did it affect the system running without a rebuild of config?
> > > > > 
> > > > > 
> > > > > Scroll up a bit, I posted a step by step
> > > > 
> > > > 
> > > > This? sudo wget https://raw.githubusercontent.com/homebridge/homebridge-raspbian-image/latest/stage3_homebridge/01-homebridge/files/hb-config-new -O=/usr/local/sbin/hb-config-new ; sudo chmod +x /usr/local/sbin/hb-config-new
> > > 
> > > 
> > > Keep scrolling. That is one step and that version has a typo in it.
> > 
> > 
> > Don't worry, I'm too scared at trying if I have to pull it together, if you have a moment it would be good for all steps and commands on this response. It would be highly appreciated
> 
> I already did. Keep scrolling.
> 
> [#1913 (comment)](https://github.com/homebridge/homebridge-config-ui-x/issues/1913#issuecomment-1847676218)

That worked a charm, big thanks :)

**Comment by NorthernMan54** [comment]
@jonnyborbs I have a working theory on what happened with hb-config, and would like your opinion if it makes makes sense.

1 - Back in late November the hb-config file was truncated on the homerbidge-raspbian-image repo.  ( This was done as the first step in merging hb-config-new back into hb-config )

2 - In your case on Dec 2, you had ran hb-config and used the update command ( This would have run normally, but it downloaded the blank file and would have broken the file)

3 - Yesterday you tried the command again, and discovered it was missing.

Does this make sense ?

**Comment by jonnyborbs** [comment]
> @jonnyborbs I have a working theory on what happened with hb-config, and would like your opinion if it makes makes sense.
> 
> 1 - Back in late November the hb-config file was truncated on the homerbidge-raspbian-image repo. ( This was done as the first step in merging hb-config-new back into hb-config )
> 
> 2 - In your case on Dec 2, you had ran hb-config and used the update command ( This would have run normally, but it downloaded the blank file and would have broken the file)
> 
> 3 - Yesterday you tried the command again, and discovered it was missing.
> 
> Does this make sense ?

Everything about it except my not remembering having done this ☹️ `.bash_history` isn't timestamped in this OS so I can't confirm or deny this concretely, but it sounds plausible enough in the absence of something more verifiable!

**Comment by NorthernMan54** [comment]
Am thinking we can close this, as I think this is the scenario that caused the issue.  I did scour the various homebridge component code bases looking for other triggers, but did not see anything.  Am thinking that unless something else comes up, we can close this.

**Comment by jonnyborbs** [comment]
Not my issue originally but I agree FWIW, particularly since at least two other folks besides me used my workaround above successfully. Thanks for all the help!

**Comment by adavison007** [comment]
Thanks for everyone’s support, now closing
